runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.bak$
- .git
- log/*
- node_modules
- backup

handlers:
- url: /graphql
  script: graphene_gae.webapp2.graphql_application

- url: /static
  static_dir: static

- url: /.*
  script: main.app

